### ISSUE TITLE
Newer Symfony versions compatibility

### ISSUE THREAD

**Issue by FabianSchmick** [webfactory/WebfactoryLegacyIntegrationBundle#11]
Hi there,

first of all I wanted to say that this is an awesome bundle and we are using this successfully in some older projects. Thanks you sharing this.

For our current project we are using `symfony 3.4`, but it seems there are some compatibility conflicts with it. If I require the bundle it returns this console output:

```
$ composer require webfactory/legacy-integration-bundle

Using version ^1.4 for webfactory/legacy-integration-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.4.20
    - Conclusion: don't install symfony/symfony v3.4.20
    - webfactory/legacy-integration-bundle 1.4.0 requires symfony/config ~2.2 -> satisfiable by symfony/config[v2.2.0, ......, v2.8.9].
    - webfactory/legacy-integration-bundle 1.4.1 requires symfony/config ~2.2 -> satisfiable by symfony/config[v2.2.0, ......, v2.8.9].
    - don't install symfony/config v2.4.0|don't install symfony/symfony v3.4.20
    ......
    - don't install symfony/config v2.2.9|don't install symfony/symfony v3.4.20
    - Installation request for symfony/symfony (locked at v3.4.20, required as 3.4.*) -> satisfiable by symfony/symfony[v3.4.20].
    - Installation request for webfactory/legacy-integration-bundle ^1.4 -> satisfiable by webfactory/legacy-integration-bundle[1.4.0, 1.4.1].

Installation failed, reverting ./composer.json to its original content.
```

Is there any chance you can publish a newer version with compatibility for newer symfony versions? Or am I doing something wrong and it should work installing?

**Comment by mpdude** [comment]
I'll leave this open for some time, maybe others want to test it as well and report back. 

Once we merge this I'll leave a short note here, so make sure to subscribe to this issue.

**Comment by mpdude** [comment]
Just changed my mind because we can still deliver fixes later on.

So, @FabianSchmick, replace `dev-relax-version-constraint` with `^1.5` in your `composer.json` file.

**Comment by FabianSchmick** [comment]
Thanks for your reply. I will let you know if I find any issues.
